version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: forky
      POSTGRES_PASSWORD: forky
      POSTGRES_DB: forky
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: